// <auto-generated />
using System;
using AbsaPhoneBook.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AbsaPhoneBook.Persistence.Migrations
{
    [DbContext(typeof(AbsaDbContext))]
    [Migration("20210126152705_datachanges")]
    partial class datachanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AbsaPhoneBook.Domain.Entities.Entry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PhonebookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryId");

                    b.HasIndex("PhonebookId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            EntryId = new Guid("ee272f8b-6096-4cb6-8625-bb4bb2d89e8b"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Bedfordview",
                            PhonebookId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            Phonenumber = "07189898989"
                        },
                        new
                        {
                            EntryId = new Guid("3448d5a4-0f72-4dd7-bf15-c14a46b26c00"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peter NorthCliff",
                            PhonebookId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            Phonenumber = "0723333333"
                        },
                        new
                        {
                            EntryId = new Guid("b419a7ca-3321-4f38-be8e-4d7b6a529319"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kensington Cape",
                            PhonebookId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            Phonenumber = "07155555555"
                        },
                        new
                        {
                            EntryId = new Guid("62787623-4c52-43fe-b0c9-b7044fb5929b"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spanish guitar hits with Manuel",
                            PhonebookId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6"),
                            Phonenumber = "0712222222"
                        },
                        new
                        {
                            EntryId = new Guid("1babd057-e980-4cb3-9cd2-7fdd9e525668"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City Stadium",
                            PhonebookId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6"),
                            Phonenumber = "0747777777"
                        },
                        new
                        {
                            EntryId = new Guid("adc42c09-08c1-4d2c-9f96-2d15bb1af299"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James Work",
                            PhonebookId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6")
                        });
                });

            modelBuilder.Entity("AbsaPhoneBook.Domain.Entities.Phonebook", b =>
                {
                    b.Property<Guid>("PhonebookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhonebookId");

                    b.ToTable("Phonebooks");

                    b.HasData(
                        new
                        {
                            PhonebookId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Personal"
                        },
                        new
                        {
                            PhonebookId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Work"
                        },
                        new
                        {
                            PhonebookId = new Guid("bf3f3002-7e53-441e-8b76-f6280be284aa"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Business"
                        },
                        new
                        {
                            PhonebookId = new Guid("fe98f549-e790-4e9f-aa16-18c2292a2ee9"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leisure"
                        });
                });

            modelBuilder.Entity("AbsaPhoneBook.Domain.Entities.Entry", b =>
                {
                    b.HasOne("AbsaPhoneBook.Domain.Entities.Phonebook", "Phonebook")
                        .WithMany("Entries")
                        .HasForeignKey("PhonebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
